// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

// ignore_for_file: lines_longer_than_80_chars
// ignore: avoid_classes_with_only_static_members
class AppTranslation {
  static Map<String, Map<String, String>> translations = {
    'ar': Locales.ar,
    'en': Locales.en,
  };
}

class Locales {
  static const ar = {
    'currentLocation': 'الموقع الحالي',
    'search': 'بحث',
    'mostViewItems': 'الاكثر مشاهدة',
    'seeAll': 'عرض الكل',
    'popularDestination': 'الوجهات الشعبية',
    'appName': 'وكالات بحرية',
    'lookingFor': 'ما الذي تبحث عنه',
    'makeOrder': 'اطلب الان',
    'history': 'ارشيف الطلبات',
    'recentPackages': 'الطلبات الاخيرة',
    'Pending': 'قيد الانتظار',
    'Delivered': 'تم التوصيل',
    'Tracking Id: ': 'رقم التتبع: ',
    'NotificationPage': 'الاشعارات',
    'loginForContinuo':
        'لا تفوت العروض الحصرية والمزايا. سجل الدخول الآن للاستفادة الكاملة من تطبيقنا',
    'FullName': 'الاسم بالكامل',
    'phoneNumber': 'رقم الهاتف',
    'Phone number is not valid': 'رقم الهاتف غير صحيح',
    'password': 'كلمة المرور',
    'email': 'البريد الالكتروني',
    'Forget Password?': 'نسيت كلمة المرور؟',
    'register': 'تسجيل حساب جديد',
    'login': 'تسجيل الدخول',
    'Password is very strong': 'كلمة المرور قوية جدا',
    'Password is weak most contain 8 character, 1 uppercase, 1 lowercase':
        'كلمة المرور ضعيفة يجب ان تحتوي على 8 احرف وحرف كبير وحرف صغير',
    'Password is medium': 'كلمة المرور متوسطة',
    'if you want strong password add number and special character':
        'اذا كنت تريد كلمة مرور قوية اضف رقم وحرف خاص',
    'welcome': 'مرحبا بك',
    'Loading': 'جاري التحميل',
    'Error': 'خطأ',
    'Sign up': 'تسجيل حساب جديد',
    'Hi': 'مرحبا',
    'Welcome To Maritime Agency': 'مرحبا بك في وكالات بحرية',
    'financial Year : ': 'السنة المالية : ',
    'Import and export weight': 'وزن الاستيراد والتصدير',
    'Trip Number :': 'رقم الرحلة :',
    'Trip Number': 'رقم الرحلة',
    'No Trip': 'لا يوجد رحلات',
    'Arrival Date: ': 'تاريخ الوصول: ',
    'No Date': 'لا يوجد تاريخ',
    'Exit Date: ': 'تاريخ الخروج: ',
    'Exit': 'مغادرة',
    'Arrival To Port': 'وصول الى الميناء',
    'Import weight': 'وزن الاستيراد',
    'Export weight': 'وزن التصدير',
    'Arrival Date': 'تاريخ الوصول',
    'Exit Date': 'تاريخ الخروج',
    'Success': 'تم بنجاح',
    'Trip is arrived to port': 'تم وصول الرحلة الى الميناء',
    'Terminal': 'الرصيف',
    'تاريخ الرسو': 'تاريخ الرسو',
    'لا يوجد تاريخ': 'لا يوجد تاريخ',
    'Trip is exit from terminal': 'تم خروج الرحلة من الرصيف',
    'Cancel': 'الغاء',
    'Ok': 'موافق',
    'Trip Port Terminal Page': 'الرحلة والميناء والرصيف',
    'Trip Port Page': 'الرحلة والميناء',
    'Port': 'الميناء',
    'تاريخ القدوم': 'تاريخ القدوم',
    'Not Found': 'غير موجود',
    'الرسو': 'الرسو',
    'الرسو في ': 'الرسو في ',
    'الرصيف الاول': 'الرصيف الاول',
    'الرصيف': 'الرصيف',
    'الرصيف الثاني': 'الرصيف الثاني',
    'Done': 'تم',
    'Clear': 'مسح',
    'Please select first terminal': 'الرجاء اختيار الرصيف الاول',
    'الرسو الى الرصيف': 'الرسو الى الرصيف',
    'Ship': 'الباخرة',
    'تاريخ بدء التفريغ': 'تاريخ بدء التفريغ',
    'تاريخ انتهاء التفريغ': 'تاريخ انتهاء التفريغ',
    'تاريخ بدء التحميل': 'تاريخ بدء التحميل',
    'تاريخ انتهاء التحميل': 'تاريخ انتهاء التحميل',
  };

  //
  ///
  static const en = {
    'Hi': 'Hi',
    'تاريخ انتهاء التحميل': 'Loading End Date',
    'تاريخ بدء التحميل': 'Loading Start Date',
    'تاريخ انتهاء التفريغ': 'Discharge End Date',
    'تاريخ بدء التفريغ': 'Discharge Start Date',
    'Ship': 'Ship',
    'الرسو الى الرصيف': 'Landing to terminal',
    'Please select first terminal': 'Please select first terminal',
    'Clear': 'Clear',
    'Done': 'Done',
    'الرصيف الثاني': 'Second Terminal',
    'الرصيف': 'Terminal',
    'الرسو في ': 'Landing in',
    'الرصيف الاول': 'First Terminal',
    'الرسو': 'Landing',
    'Not Found': 'Not Found',
    'تاريخ القدوم': 'Arrival Date',
    'Port': 'Port',
    'Trip Port Page': 'Trip Port Page',
    'Trip Port Terminal Page': 'Trip Port Terminal Page',
    'Ok': 'Ok',
    'Cancel': 'Cancel',
    'Trip is exit from terminal': 'Trip is exit from terminal',
    'لا يوجد تاريخ': 'No Date',
    'تاريخ الرسو': 'Arrival Date',
    'Terminal': 'Terminal',
    'Trip is arrived to port': 'Trip is arrived to port',
    'Success': 'Success',
    'Exit Date': 'Exit Date',
    'Arrival Date': 'Arrival Date',
    'Export weight': 'Export weight',
    'Import weight': 'Import weight',
    'Arrival To Port': 'Arrival To Port',
    'Exit': 'Exit',
    'Exit Date: ': 'Exit Date: ',
    'No Date': 'No Date',
    'Arrival Date: ': 'Arrival Date: ',
    'No Trip': 'No Trip',
    'Trip Number': 'Trip Number',
    'Trip Number :': 'Trip Number :',
    'Import and export weight': 'Import and export weight',
    'Welcome To Maritime Agency': 'Welcome To Maritime Agency',
    'financial Year : ': 'financial Year : ',
    'Sign up': 'Sign up',
    'What will you explore next?': 'What will you explore next?',
    'Loading': 'Loading',
    'Error': 'Error',
    'Your Shipping Address': 'Your Shipping Address',
    'Password is very strong': 'Password is very strong',
    'Password is medium': 'Password is medium',
    'if you want strong password add number and special character':
        'if you want strong password add number and special character',
    'Password is weak most contain 8 character, 1 uppercase, 1 lowercase':
        'Password is weak most contain 8 character, 1 uppercase, 1 lowercase',
    'register': 'Register',
    'login': 'Login',
    'Forget Password?': 'Forget Password?',
    'email': 'Email',
    'password': 'Password',
    'Phone number is not valid': 'Phone number is not valid',
    'phoneNumber': 'Phone Number',
    'FullName': 'Full Name',
    'loginForContinuo':
        'Don\'t miss out on exclusive features and benefits. Sign in now to take full advantage of our app!',
    'Tracking Id: ': 'Tracking Id: ',
    'NotificationPage': 'Notification',
    'Delivered': 'Delivered',
    'Pending': 'Pending',
    'recentPackages': 'Recent Packages',
    'search': 'Search',
    'lookingFor': 'What are you looking for?',
    'history': 'Package History',
    'seeAll': 'View All',
    'makeOrder': 'Make Order',
    'popularDestination': 'Popular Destination',
    'appName': 'Maritime Agency',
  };
}
